Refacto make loaders manage es
139bercy/pypel pull request #88
Opened 2021-09-29 10:36 UTC by loldebyte

## Description

## Motivation and Context
Closes #79 

## How Has This Been Tested?
regular test suite

## Screenshots (if appropriate):

## Types of changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-09-30 08:22 UTC, edaubert commented on pypel/loaders/Loaders.py
> +                 path_to_export_folder: Union[None, str, bytes, os.PathLike] = None,
Je ne comprends pas pourquoi ici nous avons la configuration pour ES et la configuration pour le stockage sur disque.

Cela devrait être 2 loaders différents ayant donc des paramètres différents.

En les séparant, cela rajoute des fichiers mais cela permet de simplifier le code dans chacun.
De plus le code est spécifique à un cas d'usage et pas à plusieurs (envoi sur ES ou enregistrement dans un dossier)

2021-09-30 08:22 UTC, edaubert commented on pypel/loaders/Loaders.py
> +        if "cafile" in es_config:
As-tu vérifié dans data360 ?

De mêmoire, je n'avais pas ce `if` sur le cafile.

2021-09-30 08:24 UTC, loldebyte commented on pypel/ProcessFactory.py
> +        ...                          "es_config": {"user": "elastic",
Bonne remarque, faut que je rajoute un example SSL...

2021-09-30 08:48 UTC, loldebyte commented on pypel/loaders/Loaders.py
> +                 path_to_export_folder: Union[None, str, bytes, os.PathLike] = None,
ça devrait effectivement être 2 loaders séparés, mais imo c'est pas urgent vu qu'il faudrait soit permettre d'avoir 2 loaders en un process, soit utiliser 2 process pour conserver ce comportement.
Au passage, ce serait un breaking change et c'est à ce genre ce changements que je fais allusion quand je dis que pypel n'est pas stable

2021-09-30 08:49 UTC, loldebyte commented on pypel/loaders/Loaders.py
> +        if "cafile" in es_config:
J'ai récupéré ce snippet depuis [data360](https://github.com/139bercy/DATAFIN360/blob/90307078f9474d4d056bdccf3242fe20a2af288b/scripts_python/main.py#L38)

2021-10-01 09:08 UTC, loldebyte commented on pypel/ProcessFactory.py
> +            return class_(**instance_config)
J'ai juste changé le nom de la variable, le comportement devrait être identique

2021-10-01 09:17 UTC, edaubert commented on pypel/loaders/Loaders.py
> +                 path_to_export_folder: Union[None, str, bytes, os.PathLike] = None,
Normalement on a pas de cas d'usage ou l'on veut 2 loaders.

Et même si c'était le cas, je pense que l'on définirait 2 process distinct qui travail sur le même fichier.

Pour l'instant si tu préfères laisser comme ça, ce n'est pas non plus problématique

2021-10-01 09:17 UTC, edaubert commented on pypel/loaders/Loaders.py
> +        if "cafile" in es_config:
Moi je pensais plutôt à cette version : https://github.com/139bercy/orchestrator-ETL/blob/master/default-ETL/main.py#L22

Qui du coup est dans Orchestrator-ETL et utilisé dans data360.
Mais j'ai l'impression que c'est la même chose or je suis quasiment sûr que j'avais une version sans `ca_file`.
Enfin bon tanpis

2021-10-01 09:34 UTC, loldebyte commented on pypel/loaders/Loaders.py
> +                 path_to_export_folder: Union[None, str, bytes, os.PathLike] = None,
Jusqu'à présent, ça me paraissait étrange de séparer en deux process distincts un traitement qui devrait être factorisable : dans le cas avec 2 process on aurait `fichier -> E -> T -> L -> fichier -> E -> L -> ELK`, j'étais partisant d'éviter à avoir a dupliquer l'extract, c'est pour ça que j'envisageais de passer par 2 Loaders, c'est aussi pour ça que le Loader originel fait 2 choses en même temps.
Maintenant, c'est vrai que si cette "duplication" de l'extract permet de simplifier considérablement le code et la logique, ça vaut probablement le coup, au moins dans un premier temps.
Tout ça serait considérablement plus simple s'il était possible de configurer ou les différentes classes `E`, `T` et `L` envoient leur données, mais à ce niveau là il faudrait peut être envisager d'utiliser NiFi...

2021-10-05 10:08 UTC, kaa-serpent requested changes

2021-10-05 10:08 UTC, kaa-serpent commented on tests/unit/test_Loader.py
> +        es_instanciating_loader._instantiate_es({"user": "elastic", "pwd": "changeme", "host": "1.12.4.2", "scheme": "https", "port": 8080,
pwd devrait être `"my_pwd"` au lieu de changeme pour les tests non ?

2021-10-05 10:08 UTC, kaa-serpent commented on tests/unit/test_unit_process.py
> +        print("mock_calls", Process.process.mock_calls)
print ? utiliser log

2021-10-05 10:59 UTC, loldebyte commented on tests/integration/test_cli.py
> +            select_process_from_config(None, "", "")
Pour se conformer au type-hinting de la fonction, tout bêtement

2021-10-05 11:04 UTC, loldebyte commented on tests/unit/test_Loader.py
> +        es_instanciating_loader._instantiate_es({"user": "elastic", "pwd": "changeme", "host": "1.12.4.2", "scheme": "https", "port": 8080,
On check contre "changeme" ligne 128

2021-10-05 12:12 UTC, loldebyte commented on tests/integration/test_cli.py
> +        actual = get_args(["-f", "/file", "-c", "/home/user/pypel_conf.json", "-p", "MYPROCESS"])
C'est un chemin en dur, mais j'aurais pu mettre `chimpanzé_fait_du_trampoline` que ç'aurait été pareil, je vérifie juste que la chaine passée en entrée est identique ou cohérente avec celle attendue

2021-10-05 12:31 UTC, kaa-serpent commented on tests/unit/test_Loader.py
> +        es_instanciating_loader._instantiate_es({"user": "elastic", "pwd": "changeme", "host": "1.12.4.2", "scheme": "https", "port": 8080,
ah oui, j'ai mal lu

2021-10-05 12:35 UTC, kaa-serpent approved these changes

2021-10-05 13:02 UTC, merged